apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: app1
        image: brahimhamdi/app:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: SRV1
spec:
  selector:
    app: myapp
  ports:
    - port: 2000
      targetPort: 2000
      nodePort: 32001
      protocol: TCP
  type: NodePort
